version: '3'
services:
  beta_backend:
    container_name: beta_backend
    hostname: beta_backend
    build:
      context: ./betauia
      dockerfile: Dockerfile
    ports:
      - 5001:80

  beta_frontend:
    container_name: beta_frontend
    hostname: beta_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - beta_backend
