version: '3'
services:
  beta_backend:
    restart: always
    container_name: beta_backend
    hostname: beta_backend
    volumes:
     - ./betauia/wwwroot/qr/:/app/wwwroot/qr
     - ./betauia/wwwroot/Uploads/:/app/wwwroot/Uploads
    build:
      context: ./betauia
      dockerfile: Dockerfile
    ports:
      - 5001:80

  beta_frontend:
    restart: always
    container_name: beta_frontend
    hostname: beta_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - beta_backend
volumes:
  pgdata:

