version: '3'
services:
  beta_backend:
    container_name: beta_backend
    hostname: beta_backend
    build:
      context: ./betauia
      dockerfile: Dockerfile
    ports:
      - 5001:80

  beta_frontend:
    container_name: beta_frontend
    hostname: beta_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/front
      - ./frontend/node_modules
    environment:
      - PORT=80
    depends_on:
      - beta_backend

  beta_nginx:
    container_name: beta_nginx
    hostname: beta_ngnix
    image: nginx:alpine
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '8080:8080'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/static:/var/www/static
    depends_on:
      - beta_frontend

