version: '3'
services:
  beta_backend:
    restart: always
    container_name: beta_backend
    hostname: beta_backend
    volumes:
     - ./betauia/wwwroot/qr/:/app/wwwroot/qr
     - ./betauia/wwwroot/Uploads/:/app/wwwroot/Uploads
    build:
      context: ./betauia
      dockerfile: Dockerfile
    ports:
      - 5001:80
    links:
      - beta_redis
    depends_on:
      - beta_redis

  beta_frontend:
    restart: always
    container_name: beta_frontend
    hostname: beta_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - beta_backend
  beta_redis:
    restart: always
    image: redis:alpine
    container_name: beta_redis
    hostname: beta_redis
    volumes:
     - ${redis_store}:/data
