version: '3'
services:
  beta_backend:
    restart: always
    container_name: beta_backend
    hostname: beta_backend
    build:
      context: ./betauia
      dockerfile: Dockerfile-Prod
    ports:
      - 5001:80
    links:
      - beta_db
      - beta_redis
    depends_on:
      - beta_db
      - beta_redis

  beta_frontend:
    restart: always
    container_name: beta_frontend
    hostname: beta_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-Prod
    network_mode: host
    depends_on:
      - beta_backend

  beta_db:
    image: postgres
    restart: always
    container_name: beta_db
    hostname: beta_db
    environment:
      POSTGRES_PASSWORD: 'hackmeuser'
      POSTGRES_USER: 'boiis'
      POSTGRES_DB: 'beta_db'
    ports:
      - 5432:5432

  beta_redis:
    restart: always
    image: redis:alpine
    container_name: beta_redis
    hostname: beta_redis
    volumes:
     - ${redis_store}:/data

volumes:
  db_data: {}