FROM mcr.microsoft.com/dotnet/core/sdk:2.2.105


# Required inside Docker, otherwise file-change events may not trigger
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

# Set a working dir at least 2 deep. The output and intermediate output folders will be /code/obj and /code/bin
WORKDIR /app

# By copying these into the image when building it, we don't have to re-run restore everytime we launch a new container
COPY *.csproj .
COPY . ./
RUN dotnet restore
# This will build and launch the server in a loop, restarting whenever a *.cs file changes
ENTRYPOINT dotnet watch run --no-restore